### ISSUE TITLE
Install Create MyHMI 3GL_06.23.00.00 Question

### ISSUE THREAD

**Issue by xkp-1992** [alxcor/cam840#1]
Due to the lack of QT5.0 authorization key, the QT Installation and VirtualBox VM options are not checked for installation. QT examples, lack of build linux tools, etc., how can I get these missing items?

**Comment by alxcor** [comment]
As far as I know, you need to install both VisualStudio and QT with license in order to use Create MyHMI 3GL.

**Comment by xkp-1992** [comment]
Yes, this was verified in 3gl_v6.23, but in the installation 3gl_v4.92 version, 3gl was found to conflict with vs2017, the specific dll is Microsoft.VisualStudio.Setup.Configuration.Native.dll, i.e. after installing vs2017 first, 3gl could not be installed, and there was a crash.

**Comment by alxcor** [comment]
I do not have access to 4.92 or 6.23.
My tests use only 2.6, 4.5, 4.7. According to the manuals, I had to use VS2015 and Qt4.8 for all these versions.
I suppose you should read the manual to check if there is a mandatory version and, if you still have problems, to contact technical support (se page https://support.industry.siemens.com) to solve your compatibility issues.
